# Generated by Django 4.1.1 on 2023-03-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_employee_emp_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_end_date',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_start_date',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
