# Generated by Django 4.1.1 on 2023-03-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_employee_emp_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_start_date',
            field=models.DateField(),
        ),
    ]
