# Generated by Django 4.1.1 on 2023-03-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_employee_emp_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
