# Generated by Django 4.1.1 on 2023-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_employee_emp_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
