# Generated by Django 4.1.1 on 2023-03-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_employee_emp_no_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.IntegerField(unique=True),
        ),
    ]
